Updated example for PIXI.Geometry to draw a square instead of dovetail
pixijs/pixijs pull request #10225
Opened 2024-02-17 10:45 UTC by himakhaitan

##### Description of change

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

2024-02-17 10:46 UTC, himakhaitan commented
Issue Code is: #10155

2024-02-17 11:17 UTC, bigtimebuddy approved these changes
Thank you!

2024-02-17 12:36 UTC, bigtimebuddy requested changes

2024-02-17 12:36 UTC, bigtimebuddy commented on packages/core/src/geometry/Geometry.ts
> + * const geometry = new PIXI.Geometry();
We like to use import for examples instead of the global PIXI. Majority of use-cases are using bundles like Webpack.

2024-02-17 17:57 UTC, bigtimebuddy approved these changes

2024-02-17 18:15 UTC, bigtimebuddy commented on packages/core/src/geometry/Geometry.ts
> + *
```suggestion
 *
```

2024-02-17 18:15 UTC, bigtimebuddy commented on packages/core/src/geometry/Geometry.ts
> + *
```suggestion
 *
```

2024-02-18 15:18 UTC, merged

2024-02-18 15:18 UTC, bigtimebuddy commented
Thanks @himakhaitan !

2024-02-18 22:45 UTC, himakhaitan commented
It was my first Open Source Contribution. Thanks @bigtimebuddy

2024-02-18 22:46 UTC, bigtimebuddy commented
So awesome! Thank you and congrats! 🎉 we feel honored you decided to help Pixi.