Fix: roundPixels offset
pixijs/pixijs pull request #10389
Opened 2024-03-28 13:55 UTC by GoodBoyDigital

ensure pixels are rounded and not floored. 

fixes #10373

Clue was in the variable name all along :)

Thanks @FunFetched for the suggestion!

2024-03-31 13:04 UTC, ivanpopelyshev requested changes
Round is bad, do not use round: https://www.w3.org/TR/WGSL/#round-builtin

`Floor(x + 0.5)` is better,

Consider you have sprite from 3.5 to 8.5 - it gets rounded to "4 to 8" which is a pixel smaller. In case of half-pixel we have to round everything to the same side!

Btw v7 had a bug where we used `~~x` for flooring - and it floors values differently for "x>0" and "x<0", so if you ever see float->int conversion for rounding pixels - please get rid of it , use `floor`.

2024-03-31 17:07 UTC, FunFetched commented
I did just run into an edge case where the issue still appears to be happening, though not nearly as often. It seems the actual root of the problem lies further up the chain somewhere. Perhaps we're missing a Math.floor somewhere.

2024-04-02 15:47 UTC, GoodBoyDigital commented
> Floor(x + 0.5)

great feedback! thanks - will update PR

2024-04-02 17:57 UTC, ivanpopelyshev approved these changes

2024-04-09 12:59 UTC, merged