feat: add 'min' and 'max' blend modes
pixijs/pixijs pull request #10684
Opened 2024-07-03 12:11 UTC by dev7355608

##### Description of change

Added blend modes for min and max blending.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

2024-07-03 12:39 UTC, Feu-Secret approved these changes

2024-07-03 13:14 UTC, bigtimebuddy commented
Could you add a visual render test for this?

2024-07-04 13:52 UTC, bigtimebuddy approved these changes

2024-07-12 09:40 UTC, GoodBoyDigital commented on src/rendering/renderers/gl/state/mapWebGLBlendModesToPixi.ts
> +    const isWebGl2 = 'WebGL2RenderingContext' in globalThis && gl instanceof globalThis.WebGL2RenderingContext;
this one might be an issue - if user explicitly specifies WebGL 1 render, this code here assume it WebGL2

2024-07-12 09:43 UTC, GoodBoyDigital approved these changes
lgtm!

2024-07-12 10:15 UTC, Zyie requested changes

2024-07-12 10:15 UTC, Zyie commented on src/rendering/renderers/gl/state/mapWebGLBlendModesToPixi.ts
> +    const isWebGl2 = 'WebGL2RenderingContext' in globalThis && gl instanceof globalThis.WebGL2RenderingContext;
I believe we will want to use the `DOMAdapter` here to make sure this call works on all environments

e.g `const isWebGl2 = !(gl instanceof DOMAdapter.get().getWebGLRenderingContext());`

2024-07-12 11:30 UTC, Zyie approved these changes

2024-07-16 15:15 UTC, merged