fix: Filter constructor blendMode option
pixijs/pixijs pull request #10686
Opened 2024-07-04 10:59 UTC by dev7355608

##### Description of change

Add missing assignment of the `options.blendMode` to the `Filter` constructor.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

2024-07-04 18:37 UTC, GoodBoyDigital approved these changes
thanks @dev7355608 !!

2024-07-04 20:09 UTC, bigtimebuddy approved these changes

2024-07-05 08:27 UTC, Zyie requested changes

2024-07-05 08:27 UTC, Zyie commented on src/filters/Filter.ts
> +        this.blendMode = options.blendMode;
This change causes `BlurFilter` to break

We could do something like this 

```js
// Filter.ts
constructor() {
    ...
    if (options.blendMode) this.blendMode = options.blendMode;
}
```

```js
// BlurFilter.ts
constructor(){
    const { strength, quality, blendMode, ...rest } = options;
    super({
        ...rest,
        blendMode: null,
        compatibleRenderers: RendererType.BOTH,
        resources: {}
    });
    
    this.blendMode = blendMode ?? Filter.defaultOptions.blendMode;
}
```

2024-07-05 09:52 UTC, dev7355608 commented on src/filters/defaults/blur/BlurFilter.ts
> -
Also fixes a bug, I think: In the x-blur-only case the blend mode wouldn't have been applied previously.

2024-07-05 13:44 UTC, Zyie approved these changes

2024-07-09 12:47 UTC, merged