fix: clean our render lists after use!
pixijs/pixijs pull request #10745
Opened 2024-07-12 12:14 UTC by GoodBoyDigital

##### Description of change
Add some code to not retain items in the update lists after use. Should be nice and fast too!

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

2024-07-12 15:14 UTC, ivanpopelyshev requested changes
This should be done " from new length to old length" not "from new length to max length"

2024-07-15 08:01 UTC, GoodBoyDigital commented
> This should be done " from new length to old length" not "from new length to max length"

Yoo! it early outs if it hits a `null` slot, so this should not make a difference?

2024-07-15 08:06 UTC, ivanpopelyshev approved these changes

2024-07-15 09:19 UTC, Zyie approved these changes

2024-07-16 14:54 UTC, merged