Fix default type and internalFormat of GLTexture
pixijs/pixijs pull request #7438
Opened 2021-04-22 18:27 UTC by dev7355608

### Description of change

Swap the default values of `GLTexture.type` and `GLTexture.internalFormat`, because it's the wrong way around.

```
GL_UNSIGNED_BYTE = 5121
GL_RGBA          = 6408 
```

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

2021-05-10 19:44 UTC, bigtimebuddy approved these changes

2021-05-15 16:59 UTC, SukantPal requested changes

2021-05-15 16:59 UTC, SukantPal commented on packages/core/src/textures/GLTexture.ts
> +        this.type = 5121;
Let's use `import('@pixi/constants').TYPES.UNSIGNED_BYTE` instead of a number literal.

2021-05-15 16:59 UTC, SukantPal commented on packages/core/src/textures/GLTexture.ts
> +        this.internalFormat = 6408;
Let's use `import('@pixi/constants').FORMATS.RGBA` instead of a number literal.

2021-05-19 21:46 UTC, ivanpopelyshev approved these changes

2021-05-19 22:43 UTC, SukantPal approved these changes

2021-05-19 22:59 UTC, merged

2021-05-19 22:59 UTC, bigtimebuddy commented
Thanks @dev7355608