Remove misleading description
pixijs/pixijs pull request #7455
Opened 2021-04-28 12:59 UTC by suyingtao

##### Description of change
Description of ``BLEND_MODES`` is out of date. The WebGL renderer supports for each blend mode.

2021-04-28 13:22 UTC, bigtimebuddy approved these changes

2021-04-29 14:39 UTC, SukantPal commented
Does it really? cc @ivanpopelyshev (then pixi-picture is obsolete?)

2021-04-29 14:48 UTC, ivanpopelyshev commented
pixi-picture works through filters, and i didnt move it to v6 yet.

No, OVERLAY/HARDLIGHT and others still have to go through filters.

However, all composition modes (DST_IN and such) are supported now, we might alter that comment, @suyingtao is right about that.

2021-04-29 15:02 UTC, SukantPal commented
Then I'd would ask that the documentation reflect this information instead of simply removing mention of the exceptions.

2021-05-04 20:48 UTC, bigtimebuddy commented
Can someone propose a better description about blend modes?

2021-05-09 20:12 UTC, SukantPal commented
We just need to list the unsupported blend modes in the description.

2021-05-10 18:29 UTC, bigtimebuddy requested changes
@suyingtao Thanks for this, but I think this need to be tweaked. Here are the list of blend modes supported on WebGL only (Canvas can support all):

NORMAL
ADD
MULTIPLY
SCREEN
ADD_NPM
SCREEN_NPM
NONE
SRC_IN
SRC_OUT
SRC_ATOP
DST_OVER
DST_IN
DST_OUT
DST_ATOP
SUBTRACT
ERASE
XOR

2021-05-19 20:51 UTC, bigtimebuddy commented
After a lot of inactivity, I'm going to close this. Someone is welcome to do an update here or @suyingtao happy to re-open if you want to make the fixes.

2021-05-19 20:51 UTC, closed without merging