Update README.md
pixijs/pixijs pull request #7721
Opened 2021-08-18 18:00 UTC by BhargaviChada

Added link to guides in the learn section.

##### Description of change

Added link to guides in learn section.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ x] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

2021-08-18 18:53 UTC, ivanpopelyshev approved these changes

2021-08-18 19:12 UTC, bigtimebuddy requested changes

2021-08-18 19:12 UTC, bigtimebuddy commented on README.md
> +- Guide: Supplementary resource to the API documentation [here](https://github.com/pixijs/guides/tree/main/docs).
Link should be https://pixijs.io/guides

2021-08-20 08:29 UTC, domis86 commented
when merged it should close task #7617

2021-08-20 09:36 UTC, BhargaviChada commented
> when merged it should close task #7617

Sorry forgot to mention 'Closes #7616' in the previous commit

2021-08-20 10:00 UTC, bigtimebuddy approved these changes
Thank you!

2021-09-08 20:16 UTC, merged