Fix setting precision of shader
pixijs/pixijs pull request #7847
Opened 2021-10-04 21:55 UTC by dev7355608

##### Description of change

`setPrecision` always prepended a precision statement, because the shader name was prepended first. I'm not sure which statement would define the precision of the shader in this case. Also we never entered the second branch in `setPrecision`, which could leave a `highp` in there that isn't supported. So I fixed that. `setPrecision` also potentially changed highp integers to mediump in the second branch, but the documentation only mentions floats, so I changed that as well.

```glsl
precision highp float;
#define SHADER_NAME pixi-shader-3
precision lowp float;

attribute vec2 aVertexPosition;
attribute vec2 aVertexPosition2;

uniform mat3 projectionMatrix;
uniform mat3 translationMatrix;

void main() {
    gl_Position = vec4((projectionMatrix * translationMatrix * vec3(aVertexPosition + aVertexPosition2, 1.0)).xy, 0.0, 1.0);
}
```

I also improved the `#version` detection in the program constructor. I split the sources in two parts and insert the shader name and precision statement in-between. Shaders with version statement are no longer handled differently than shaders without.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

2021-10-04 22:27 UTC, ivanpopelyshev approved these changes

2021-10-04 22:28 UTC, ivanpopelyshev commented
Possible alternative approach: https://github.com/pixijs/tilemap/blob/7972c60b1154e6cfc5f1344300706f69b3b386eb/src/tilemap.frag#L2-L6

The important thing is, whatever we do, people will have to check how their stuff works on meidump because if uniform is highp in one shader and mediump in another, it wont link.

2021-10-04 22:30 UTC, ivanpopelyshev requested changes
actually, no, I cant accept that.

Currently, all shaderws with `#version` wont be modified.
My concern is that there has to be a way to use shader as user wants, without our preprocessor. 

@GoodBoyDigital is doing new preprocessor API, for several months already - then we'll be able to make better changes to the algo.

Without this invariant I cant accept this thing.

2021-10-04 23:09 UTC, dev7355608 commented
I see, and a new preprocessor API sounds good. Do you want me to revert the `#version` part, but keep the changes to `setPrecision`?

2021-10-04 23:32 UTC, ivanpopelyshev commented
Yep. If there's `#version` - we dont modify shader at all.

2021-10-05 03:26 UTC, ShukantPal requested changes
Can this be tested?

2022-04-16 11:18 UTC, closed without merging