Fix incorrect BitmapText text width calculation (#7758)
pixijs/pixijs pull request #7933
Opened 2021-10-31 02:18 UTC by kjarrio

##### Description of change
Fix for BitmapText width calculation when using monospace fonts. Fixes issue #7758 - and doesn't break PR #7479 / #7245

##### Pre-Merge Checklist
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

2021-10-31 06:11 UTC, kjarrio commented
Example: https://codesandbox.io/s/festive-cartwright-7ruly?file=/index.html

2021-10-31 11:19 UTC, bigtimebuddy commented
Thank you for the PR! Could you possibly add unit test for this behavior?

2021-10-31 19:12 UTC, neymanushka approved these changes

2021-11-01 15:35 UTC, bigtimebuddy commented on packages/text-bitmap/src/BitmapText.ts
> +        lastLineWidth += Math.abs(xOffsetWidthComp);
```suggestion

        lastLineWidth += Math.abs(xOffsetWidthComp);
```

2021-11-06 19:19 UTC, kjarrio commented
Here is work in progress, for proper width/height calculations for BitmapTexts:

Before: https://63hr2.csb.app PixiJS 6.2.0 (Source: https://codesandbox.io/s/boring-shadow-63hr2?file=/index.html )
After: https://wiwen.csb.app (Source: https://codesandbox.io/s/tender-violet-wiwen?file=/index.html )

I have the unit tests as well, but I'm still working on a few edge cases for "pixel perfection" but I'm unsure if it's even worth it. For me, it's "good enough" with those changes. How important is it to get this 100%?

I'll tidy up the code to finish this PR as soon as I have time.

2021-12-13 18:50 UTC, bigtimebuddy commented
Sorry it's taken a long time to review!

Seeing two issues here with width in your recent examples:

"C" is hanging off:
![Screen Shot 2021-12-13 at 1 49 00 PM](https://user-images.githubusercontent.com/864393/145870528-a5a3c220-80e0-4f02-a8f4-1245d15484a7.png)

Character endings are peaking out:
![Screen Shot 2021-12-13 at 1 49 05 PM](https://user-images.githubusercontent.com/864393/145870529-39bc4e08-f97d-47d9-9c9c-a84701988c41.png)

2022-01-11 09:17 UTC, kozickikarol commented
@kjarrio Are you going to fix something here? I would gladly use new version with your fix cause I encounter the same problem.

2022-01-11 16:17 UTC, bigtimebuddy approved these changes
This isn't perfect, but it's good enough. If we can improve it overtime that'd be great.

2022-01-12 09:37 UTC, kozickikarol commented
> This isn't perfect, but it's good enough. If we can improve it overtime that'd be great.

🎉 
@bigtimebuddy Any chance to have it in upcoming 6.2.2? It blocks our project from migrating to v6.

2022-01-19 13:53 UTC, kozickikarol commented
@kjarrio I tested it more on my monospaced fonts and I noticed that this solution does not work for fonts which has xadvance<width or negative xoffset. BitmapText behaves correctly when I change digits inside but when first or last digit changes, BitmapText starts shaking.

monospaced font with negative xoffset:
[monospace_font.zip](https://github.com/pixijs/pixijs/files/7897559/monospace_font.zip)

Same font works correctly in pixi v5.

2022-04-27 05:56 UTC, joel-Yolted commented
as @kozickikarol pointed this fix does not solve the issue, There is still a clear regression made by  the original #7245 fix breaking xAdvance and incorrectly calculates the lastLineWidth of the character when xAdvance is used as shown with the original recreation on #7758 using 3.6.0  https://jsfiddle.net/1zyrd4s8/
It seems to be only occurring when anchor is set to 0.5 but that is a common use case.

Was this an intentional break? and if so please advice on why.

2022-04-27 12:06 UTC, bigtimebuddy requested changes
This needs more work based on the feedback here with negative offsets.

2022-05-23 14:56 UTC, bigtimebuddy commented
Ping @kjarrio do you want to continue working on this? If not I'd like to close and maybe someone else can pick-up this work.

2022-05-23 16:31 UTC, kjarrio commented
I will work on this, starting today, I can't promise I'll be able to fix it, but I will try to get this perfect this week

2024-12-11 20:49 UTC, Zyie commented
Hey,

Thank you for putting together this PR! Since we've moved to the next major version of the library, we're closing this to focus on the updated codebase. If this is still relevant, feel free to submit a new PR for the latest version.

2024-12-11 20:49 UTC, closed without merging