fix: allow mask to be null or undefined
pixijs/pixijs pull request #9962
Opened 2023-12-08 16:20 UTC by Zyie

fixes #9953

2023-12-08 17:06 UTC, bigtimebuddy commented on src/scene/container/container-mixins/effectsMixin.ts
>      filters?: Filter | Filter[];
While we are here, what about `filters`? Shouldn't that allow null/undefined as well?

2023-12-08 17:06 UTC, bigtimebuddy approved these changes

2023-12-11 08:08 UTC, achamas-playco commented on src/scene/container/container-mixins/effectsMixin.ts
> +    mask?: number | Container | null | undefined;
Being an optional type it implicitly accepts `undefined` so you just need to add `null`.
```suggestion
    mask?: number | Container | null;
```

2023-12-11 08:08 UTC, achamas-playco requested changes
Being an optional type it implicitly accepts `undefined` so you just need to add `null`.

2023-12-14 11:31 UTC, achamas-playco approved these changes

2023-12-14 11:37 UTC, merged